coal_blending/urls.py
from django.urls import path

from . import views

app_name = 'coal_blending'
urlpatterns = [
    path('', views.redirect_home, name='home'),
    path('data_input/', views.DataInputView.as_view(), name='data_input'),
    path('result/', views.ResultView.as_view(), name='result'),
    
    path('trigger_optimizer', views.trigger_optimizer, name='trigger_optimizer'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns = [
    path('', include('coal_blending.urls')),
    path('admin/', admin.site.urls),
    path('django-rq/', include('django_rq.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web/config/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

coal_blending/models.py
from django.db import models

# Create your models here.

coal_blending/views.py
from django.conf import settings
from django.shortcuts import redirect, render
from django.views import generic

from .models import *
from .optimize import *


def redirect_home(request):
    return redirect('coal_blending:data_input')


class DataInputView(generic.TemplateView):
    template_name = 'coal_blending/data_input.html'
    
    def get_context_data(self, **kwargs):
        context = super(DataInputView, self).get_context_data(**kwargs)
        
        url = input_url
        context['link'] = url

        # Find a workbook by url
        sheet = client.open_by_url(url)
        worksheet = sheet.worksheet('Coal_Data')
        coal_df = pd.DataFrame(worksheet.get_all_records())
        coal_df.set_index('Supplier', inplace=True)
        coal_df = coal_df.astype('float')
        context['df1'] = coal_df.to_html(table_id='Table1', classes='table table-bordered table-hover table-responsive')
        
        worksheet = sheet.worksheet('Limit_CFB12')
        limit_cfb12_df = pd.DataFrame(worksheet.get_all_records())
        limit_cfb12_df.dropna(inplace=True)
        context['df2'] = limit_cfb12_df.to_html(table_id='Table2', classes='table table-bordered table-hover table-responsive')
        
        worksheet = sheet.worksheet('Limit_CFB3')
        limit_cfb3_df = pd.DataFrame(worksheet.get_all_records())
        limit_cfb3_df.dropna(inplace=True)
        context['df3'] = limit_cfb3_df.to_html(table_id='Table3', classes='table table-bordered table-hover table-responsive')
        
        worksheet = sheet.worksheet('Shipment')
        shipment_df = pd.DataFrame(worksheet.get_all_records())
        shipment_df.set_index('Date', inplace=True)
        shipment_df.dropna(inplace=True)
        context['df4'] = shipment_df.to_html(table_id='Table4', classes='table table-bordered table-hover table-responsive')
                
        worksheet = sheet.worksheet('Operation')
        op_df = pd.DataFrame(worksheet.get_all_records())
        op_df.set_index('Date', inplace=True)
        op_df.dropna(inplace=True)
        context['df5'] = op_df.to_html(table_id='Table5', classes='table table-bordered table-hover table-responsive')
                
        return context


def trigger_optimizer(request):
    coal_optimize.delay()
    
    return redirect(request.META.get('HTTP_REFERER'))

class ResultView(generic.TemplateView):
    template_name = 'coal_blending/result.html'
    
    def get_context_data(self, **kwargs):
        context = super(ResultView, self).get_context_data(**kwargs)
        
        url = 'https://docs.google.com/spreadsheets/d/1N2EiCGQMSnxOmzuFyE6cnwrLoBTLdrjF-h7l2cUpAo0/edit#gid=979337795'
        context['link'] = url
                
        return context

coal_blending/templates/coal_blending/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/png" href="https://www.gpscgroup.com/storage/favicon.png">
    <link rel="stylesheet" type="text/css" href="{% static 'fontawesome/css/all.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'adminlte/css/adminlte.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'coal_blending/css/base.css' %}">
    {% block css %}{% endblock %}
    <title>Coal Blending Optimization | {% block title %}{% endblock %}</title>
</head>

<body class="hold-transition sidebar-mini sidebar-collapse">
<!-- Site wrapper -->
<div class="wrapper">
    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-gray-dark navbar-dark">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'coal_blending:home' %}" data-toggle="tooltip" title="Home Page"><i class="fas fa-home"></i></a>
            </li>
        </ul>

        <!-- SEARCH FORM -->
        <form class="form-inline ml-auto mr-3 my-0" action="{% url 'coal_blending:data_input' %}" method="get">
            <div class="input-group input-group-sm">
                <input class="form-control form-control-navbar" name="q" type="search" placeholder="Search" aria-label="Search" value="{{ q }}">
                <div class="input-group-append">
                    <button class="btn btn-navbar" type="submit">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </div>
        </form>

        <!-- Right navbar links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link d-flex align-items-center p-0" href="{% url 'admin:index' %}" tabindex="-1">
                    <i class="fas fa-user-cog"></i>
                </a>
            </li>
            <span class="d-none d-xl-block">
                <li class="nav-item d-flex align-items-center p-0"><a id="Clock" class="nav-link" tabindex="-1" aria-disabled="true">{% now "D, j M Y, H:i:s" %}</a></li>
            </span>
        </ul>
    </nav>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <!-- Brand Logo -->
        <a href="{% url 'coal_blending:home' %}" class="brand-link">
            <img src="{% static 'coal_blending/images/logo-white.png' %}" alt="GPSC Logo" class="brand-image img-circle elevation-3" style="opacity: 0.8">
            <span class="brand-text font-weight-light"><strong>&nbsp;&nbsp;&nbsp;Website Menu</strong></span>
        </a>

        <!-- Sidebar -->
        <div class="sidebar">
            <!-- Sidebar Menu -->
            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                    <!-- Add icons to the links using the .nav-icon class with font-awesome or any other icon font library -->
                    <li class="nav-item">
                        <a href="{% url 'coal_blending:data_input' %}" class="nav-link {% block nav_item_data_input %}{% endblock %}">
                            <i class="nav-icon fas fa-table"></i>
                            <p>Data Input</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'coal_blending:result' %}" class="nav-link {% block nav_item_result %}{% endblock %}">
                            <i class="nav-icon fas fa-poll"></i>
                            <p>Result</p>
                        </a>
                    </li>
                </ul>
            </nav>
            <!-- /.sidebar-menu -->
        </div>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        {% if messages %}
        <div class="alert alert-secondary" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            {% for message in messages %}
            {{ message }}<br>
            {% endfor %}
        </div>
        {% endif %}
        {% block body %}
        {% endblock %}
    </div>
    <!-- /.content-wrapper -->

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->

</div>
<!-- ./wrapper -->
</body>

<script type="text/javascript" src="{% static 'jquery/js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'popper/js/popper.min.js' %}"></script>
<script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'adminlte/js/adminlte.min.js' %}"></script>
<script type="text/javascript" src="{% static 'moment/js/moment.min.js' %}"></script>
<script type="text/javascript" src="{% static 'coal_blending/js/base.js' %}"></script>
{% block javascript %}
{% endblock %}
</html>

coal_blending/templates/coal_blending/dashboard.html
{% extends 'coal_blending/base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'datatables/css/datatables.min.css' %}">
<script type="text/javascript" src="{% static 'coal_blending/css/dashboard.css' %}"></script>
{% endblock %}

{% block title %}Dashboard{% endblock %}
{% block nav_item_dashboard %}active{% endblock %}

{% block body %}
<section class="content-header">
    <div class="container-responsive d-flex justify-content-center">
        <h1 class="font-weight-bold">Coal Blending</h1>
    </div>
</section>
<section class="content">
    <div class="container-fluid">
        Link to coal_spec file: <a href={{ link }}>{{ link }}</a>
        {{ df|safe }}
    </div>
</section>
{% endblock %}

{% block javascript %}
<script type="text/javascript" src="{% static 'datatables/js/datatables.min.js' %}"></script>
<script type="text/javascript" src="{% static 'coal_blending/js/dashboard.js' %}"></script>
{% endblock %}

coal_blending/templates/coal_blending/data_input.html
{% extends 'coal_blending/base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'datatables/css/datatables.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'coal_blending/css/data_input.css' %}">
{% endblock %}

{% block title %}Data Input{% endblock %}
{% block nav_item_data_input %}active{% endblock %}

{% block body %}
<section class="content-header">
    <div class="container-responsive d-flex justify-content-center">
        <h1 class="font-weight-bold">Data Input</h1>
    </div>
</section>
<section class="content">
    <div class="container-fluid">
        <div class="row">
            Link to coal_spec file:&nbsp;<a href={{ link }}>{{ link }}</a>
        </div>
        <br>
        <div class="row">
            <div class='col table-responsive'>{{ df1|safe }}</div>
        </div>
        <br>
        <div class="row">
            <div class='col table-responsive'>{{ df2|safe }}</div>
            <div class='col table-responsive'>{{ df3|safe }}</div>
        </div>
        <br>
        <div class="row">
            <div class='col table-responsive'>{{ df4|safe }}</div>
            <div class='col table-responsive'>{{ df5|safe }}</div>
        </div>
    </div>
</section>
{% endblock %}

{% block javascript %}
<script type="text/javascript" src="{% static 'datatables/js/datatables.min.js' %}"></script>
<script type="text/javascript" src="{% static 'coal_blending/js/data_input.js' %}"></script>
{% endblock %}

coal_blending/templates/coal_blending/result.html
{% extends 'coal_blending/base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'datatables/css/datatables.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'coal_blending/css/result.css' %}">
{% endblock %}

{% block title %}Optimization Result{% endblock %}
{% block nav_item_result %}active{% endblock %}

{% block body %}
<section class="content-header">
    <div class="container-responsive d-flex justify-content-center">
        <h1 class="font-weight-bold">Optimization Result</h1>
    </div>
</section>
<section class="content">
    <div class="container-fluid">
        <div class="row">
            Link to result file:&nbsp;<a href={{ link }}>{{ link }}</a>
        </div>
        <div class="row">
            <a class="btn btn-primary" href="{% url 'coal_blending:trigger_optimizer' %}" role="button">Run Optimize</a>
        </div>
    </div>
</section>
{% endblock %}

{% block javascript %}
<script type="text/javascript" src="{% static 'datatables/js/datatables.min.js' %}"></script>
{% comment %} <script type="text/javascript" src="{% static 'coal_blending/js/result.js' %}"></script> {% endcomment %}
{% endblock %}

templates/django_tables2/bootstrap4-responsive.html
{% extends 'django_tables2/bootstrap4.html' %}

{% block table-wrapper %}
<div class="table-container table-responsive">
    {% block table %}
    {{ block.super }}
    {% endblock table %}

    {% block pagination %}
    {% if table.page and table.paginator.num_pages > 1 %}
    {{ block.super }}
    {% endif %}
    {% endblock pagination %}
</div>
{% endblock table-wrapper %}